version: '3'

services:
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - wordpress_db
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - web
      - default
    environment:
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
    links:
      - wordpress_db:mysql
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:api.yepstepz.io
      - traefik.port=80
  wordpress_db:
    image: mariadb
    restart: always
    networks:
      - web
      - default
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  blog:
    image: nginx:latest
    networks:
      - web
      - default
    container_name: blog
    volumes:
      - ./blog/public:/usr/share/nginx/html
    labels:
      - traefik.frontend.rule=Host:blog.yepstepz.io
      - traefik.port=80
      - traefik.enable=true
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - web
    volumes:
      - ./site:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:yepstepz.io
      - traefik.port=80
  conf:
    image: nginx:latest
    container_name: conf
    networks:
      - web
    volumes:
      - ./conf:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:conf.yepstepz.io
      - traefik.port=80
networks:
  web:
    external: true
