version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-1:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd blog && npm install
            - run: cd blog && npm run build
workflows:
    build-1:
      jobs:
        - build-1
