version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd blog && npm install
            - run: cd blog && npm run build
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir /blog/artifacts-1;
            echo "my artifact file" > /blog/artifact-1;
            mkdir /blog/artifacts;
            echo "my artifact files in a dir" > /blog/artifacts/artifact-2;
workflows:
    build-and-test:
      jobs:
        - build-and-test
