# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:10.16.2

    working_directory: ~/blog

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # build
      - run:
          name: Compile gatsbyjs site
          command: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy-prod-job:
    docker:
      - image: circleci/node:10.16.2

    working_directory: ~/blog

    steps:
      - attach_workspace:
          at: ./
      - add_ssh_keys
      - run:
          name: known_hosts sadness
          command: ssh-keyscan -H $SITE_SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: remove existing files
          command: ssh "$SITE_SSH_USER@$SITE_SSH_HOST" "rm -rf /var/www/blog/*"
      - run:
          name: scp files
          command: scp -r public "$SITE_SSH_USER@$SITE_SSH_HOST:/var/www/blog/"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-job:
          filters:
            branches:
              only:
                - master
      - deploy-prod-job:
          filters:
            branches:
              only:
                - master
          requires:
            - build-job
