version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd blog && npm install
            - run: cd blog && npm run build
            - run: |
                # tell the operating system to remove the file size limit on core dump files 
                ulimit -c unlimited
                ./dump
            - run:
                command: |
                  mkdir -p /tmp/core_dumps
                  cp core.* /tmp/core_dumps
                when: on_fail
            - store_artifacts:
                path: /tmp/core_dumps
workflows:
    build-and-test:
      jobs:
        - build-and-test
