export const ARTICLES_LIST_LOADING = 'ARTICLES_LIST_LOADING'
export const ARTICLES_LIST_FETCHED = 'ARTICLES_LIST_FETCHED'

export const ARTICLE_LOADING = 'ARTICLE_LOADING'
export const ARTICLE_FETCHED = 'ARTICLE_FETCHED'
